language: php

env:
  global:
    - secure: "a73ImjeRdD/KD3NAehVdjm7Cw+fCF+qx1eh7TTahiQyOETVIpl0CJA14AuPTha8IXv4HFWePHHqZVgtMVCC1MG/lGvSUVQIV6fbDKl6Kl8sxKIG8kdmM/3cZYZ4yQGmHX/CBr2knOn6HqjtH2Wp29xxb/wYCE+4jONja3XdYPQs="
    - SAUCE_USERNAME=brainexe

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - redis-server

before_install:
  - composer update --no-dev
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - phpunit --coverage-clover build/logs/clover.xml
