language: php

php:
  - 7.0
  - 7.1
  - hhvm

sudo: required

matrix:
  allow_failures:
    - php: hhvm

env:
  - TRAVIS_NODE_VERSION="4"

services:
  - redis-server

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout master) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node -v
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar -q
  - gem install sass
  - npm install
  - npm install -g bower grunt
  - bower install
  - grunt buildAll
  - grunt buildAll
  - php console cc

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
