language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - redis-server

before_install:
  - composer install --no-dev
  - wget https://scrutinizer-ci.com/ocular.phar -q
  - gem install sass
  - npm install
  - npm install -g bower grunt
  - bower install
  - grunt buildAll

script:
  - phpunit --coverage-clover build/logs/clover.xml --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
