#!/usr/bin/php
<?php
if (class_exists('Tideways\Profiler')) {
    \Tideways\Profiler::start(array('api_key' => 'QRRsjpAPfF2f9K38'));
}

use Symfony\Component\Console\Application;

$dic = include __DIR__ . '/src/bootstrap.php';

/** @var Application $application */
$application = $dic->get('Console');
$application->run();
