
redis:
  build: .
  dockerfile: redis/Dockerfile
  volumes:
    - redis-data:/var/lib/redis

node:
  build: .
  dockerfile: node/Dockerfile

nginx:
  build: .
  dockerfile: nginx/Dockerfile
  volumes:
      - ..:/www/homie
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - php

php:
  build: .
  dockerfile: php/Dockerfile
  volumes:
    - ..:/www/homie
    - ./php/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - redis
